### ISSUE TITLE
AttributeError: module 'pyexcel_io.manager' has no attribute 'get_writers' on import

### ISSUE THREAD

**Issue by guysoft** [pyexcel/pyexcel#118]
Hey, installed latest pyexcel and pyexcel-io.
When I run the following I get this:
```
# python3 -c "import pyexcel"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pyexcel/__init__.py", line 17, in <module>
    from .cookbook import (
  File "/usr/local/lib/python3.5/dist-packages/pyexcel/cookbook.py", line 11, in <module>
    from pyexcel.book import Book
  File "/usr/local/lib/python3.5/dist-packages/pyexcel/book.py", line 11, in <module>
    from pyexcel.sheets import Sheet
  File "/usr/local/lib/python3.5/dist-packages/pyexcel/sheets/__init__.py", line 11, in <module>
    from .sheet import Sheet
  File "/usr/local/lib/python3.5/dist-packages/pyexcel/sheets/sheet.py", line 14, in <module>
    from pyexcel.sources import SheetMeta, save_sheet, StreamAttribute
  File "/usr/local/lib/python3.5/dist-packages/pyexcel/sources/__init__.py", line 2, in <module>
    from . import file_source_output, database  # noqa
  File "/usr/local/lib/python3.5/dist-packages/pyexcel/sources/file_source_output.py", line 10, in <module>
    import pyexcel.renderers as renderers
  File "/usr/local/lib/python3.5/dist-packages/pyexcel/renderers/__init__.py", line 6, in <module>
    from . import _texttable, _excel
  File "/usr/local/lib/python3.5/dist-packages/pyexcel/renderers/_excel.py", line 9, in <module>
    class ExcelRenderer(Renderer):
  File "/usr/local/lib/python3.5/dist-packages/pyexcel/renderers/_excel.py", line 12, in ExcelRenderer
    tuple(manager.get_writers()))
AttributeError: module 'pyexcel_io.manager' has no attribute 'get_writers'
```

**Comment by chfw** [comment]
hmm.. strange. Could you show me your `pip freeze` output?

**Comment by guysoft** [comment]
My bad, upgrading fixed the issue

**Comment by aiporre** [comment]
to which version did you update it?

**Comment by guysoft** [comment]
Lastest
