### ISSUE TITLE
pyexcel.save_as fails with error message TypeError: render_sheet() got an unexpected keyword argument 'display_length'

### ISSUE THREAD

**Issue by ManizTech** [pyexcel/pyexcel#139]
Tried developing same code from my end. It was working until few hours from almost a day back. Keep getting the error 
Traceback (most recent call last):
  File "pyexcel.py", line 5, in <module>
    sheet.save_as('sortables.html',display_length=10)
  File "/Users/Python/pyexcel/pyexcel/internal/meta.py", line 281, in save_as
    **keywords)
  File "/Users/Python/pyexcel/pyexcel/internal/core.py", line 43, in save_sheet
    return _save_any(a_source, sheet)
  File "/Users/Python/pyexcel/pyexcel/internal/core.py", line 55, in _save_any
    a_source.write_data(instance)
  File "/Users/Python/pyexcel/pyexcel/plugins/sources/file_output.py", line 29, in write_data
    sheet, **self._keywords)
  File "/Users/Python/pyexcel/pyexcel/renderer.py", line 85, in render_sheet_to_file
    self.render_sheet(sheet, **keywords)
TypeError: render_sheet() got an unexpected keyword argument 'display_length'

**Comment by ManizTech** [comment]
The issue is with the HTML file name. SAVE_AS function's parameter "FILENAME" should include filename.**SORTABLE**.html - SORTABLE is critical keyword to be used.
