### ISSUE TITLE
openSUSE test failures with pyexcel-0.5.7

### ISSUE THREAD

**Issue by jayvdb** [pyexcel/pyexcel#168]
This is with pyexcel-0.5.7, so failures are not so unexpected, and it is built against pyexcel-io-0.5.11, likely to be its own set of crazy surprises, and with pyexcel-xls-0.5.5 and pyexcel-xlsx-0.5.5  

Raising for my records mostly, as making that old version work is probably not useful.  But some of these errors may re-appear when packaging a latter version.

```console
[   57s] + /usr/bin/python2 /usr/bin/nosetests
[   59s] /usr/lib/python2.7/site-packages/lml/loader.py:64: UserWarning: Deprecated! since version 0.0.3. Please use scan_plugins_regex!
[   59s]   "Deprecated! since version 0.0.3. Please use scan_plugins_regex!"
[   59s] ......datos,de,prueba
[   59s] 1,2,3
[   59s]
[   62s] ...........E............................/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/deprecated.py:190: UserWarning: Deprecated usage since v0.2.2! Explicit import is no longer required. pyexcel.ext.ods is auto imported.
[   62s]   "is no longer required. %s is auto imported." % module_name)
[   62s] /home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/deprecated.py:190: UserWarning: Deprecated usage since v0.2.2! Explicit import is no longer required. pyexcel.ext.ods3 is auto imported.
[   62s]   "is no longer required. %s is auto imported." % module_name)
[   62s] /home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/deprecated.py:190: UserWarning: Deprecated usage since v0.2.2! Explicit import is no longer required. pyexcel.ext.xls is auto imported.
[   62s]   "is no longer required. %s is auto imported." % module_name)
[   62s] /home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/deprecated.py:190: UserWarning: Deprecated usage since v0.2.2! Explicit import is no longer required. pyexcel.ext.xlsx is auto imported.
[   62s]   "is no longer required. %s is auto imported." % module_name)
[   62s] /home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/deprecated.py:190: UserWarning: Deprecated usage since v0.2.1! Explicit import is no longer required. pyexcel.ext.text is auto imported.
[   62s]   "is no longer required. %s is auto imported." % module_name)
[   65s] ......................EE.............F.........E..........................................................................................................................................................................................................................................EE.....................................................................................................................................................................................
[   65s] ======================================================================

[   65s] ======================================================================
[   65s] ERROR: test_bug_fixes.test_xls_issue_11
[   65s] ----------------------------------------------------------------------
[   65s] Traceback (most recent call last):
[   65s]   File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
[   65s]     self.test(*self.arg)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/tests/test_bug_fixes.py", line 194, in test_xls_issue_11
[   65s]     sheet2.save_as(test_file)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/meta.py", line 281, in save_as
[   65s]     **keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/core.py", line 42, in save_sheet
[   65s]     a_source = SOURCE.get_writable_source(**keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/source_plugin.py", line 91, in get_writable_source
[   65s]     **keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/source_plugin.py", line 65, in get_a_plugin
[   65s]     library=source_library, **keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/source_plugin.py", line 39, in load_me_now
[   65s]     if source.is_my_business(action, **keywords):
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/plugins/__init__.py", line 51, in is_my_business
[   65s]     action)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/plugins/__init__.py", line 113, in find_file_type_from_file_name
[   65s]     constants.FILE_TYPE_NOT_SUPPORTED_FMT % (file_type, action))
[   65s] FileTypeNotSupported: File type 'json' is not supported for write.
[   65s] -------------------- >> begin captured logging << --------------------
[   65s] pyexcel.internal.source_plugin.SourcePluginManager: DEBUG: load me now:sheet-write
[   65s] pyexcel.internal.plugins.IOPluginManager: DEBUG: load <class 'pyexcel.plugins.renderers.excel.ExcelRenderer'> now for 'xls'
[   65s] pyexcel_io.plugins.IOManager: DEBUG: load <class 'pyexcel_xls.xlsw.XLSWriter'> now for 'xls'
[   65s] pyexcel.internal.source_plugin.SourcePluginManager: DEBUG: load me now:sheet-read
[   65s] pyexcel.internal.source_plugin.SourcePluginManager: DEBUG: import pyexcel.plugins.sources.memory_input.ReadExcelFileMemory
[   65s] pyexcel.internal.plugins.IOPluginManager: DEBUG: load <class 'pyexcel.plugins.parsers.excel.ExcelParser'> now for 'xls'
[   65s] pyexcel_io.plugins.IOManager: DEBUG: load <class 'pyexcel_xls.xlsr.XLSBook'> now for 'xls'
[   65s] pyexcel.internal.source_plugin.SourcePluginManager: DEBUG: load me now:sheet-write
[   65s] pyexcel.internal.source_plugin.SourcePluginManager: DEBUG: load me now:sheet-write
[   65s] pyexcel.internal.source_plugin.SourcePluginManager: DEBUG: load me now:sheet-write
[   65s] --------------------- >> end captured logging << ---------------------
[   65s]
[   65s] ======================================================================
[   65s] ERROR: test_download (test_examples.TestPyexcelServer)
[   65s] ----------------------------------------------------------------------
[   65s] Traceback (most recent call last):
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/tests/test_examples.py", line 52, in setUp
[   65s]     'pyexcel_server.py', 'app')
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/tests/test_examples.py", line 15, in load_from_file
[   65s]     py_mod = imp.load_source(mod_name, os.path.join(mod_name, file_ext))
[   65s] IOError: [Errno 2] No such file or directory
[   65s]
[   65s] ======================================================================
[   65s] ERROR: test_upload (test_examples.TestPyexcelServer)
[   65s] ----------------------------------------------------------------------
[   65s] Traceback (most recent call last):
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/tests/test_examples.py", line 52, in setUp
[   65s]     'pyexcel_server.py', 'app')
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/tests/test_examples.py", line 15, in load_from_file
[   65s]     py_mod = imp.load_source(mod_name, os.path.join(mod_name, file_ext))
[   65s] IOError: [Errno 2] No such file or directory
[   65s]
[   65s] ======================================================================
[   65s] ERROR: test_file_type_as_attribute.test_save_handsontable_html
[   65s] ----------------------------------------------------------------------
[   65s] Traceback (most recent call last):
[   65s]   File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
[   65s]     self.test(*self.arg)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/tests/test_file_type_as_attribute.py", line 224, in test_save_handsontable_html
[   65s]     save_as(array=[[1]], dest_file_name=test_file)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/core.py", line 66, in save_as
[   65s]     return sources.save_sheet(sheet, **dest_keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/core.py", line 42, in save_sheet
[   65s]     a_source = SOURCE.get_writable_source(**keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/source_plugin.py", line 91, in get_writable_source
[   65s]     **keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/source_plugin.py", line 65, in get_a_plugin
[   65s]     library=source_library, **keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/source_plugin.py", line 39, in load_me_now
[   65s]     if source.is_my_business(action, **keywords):
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/plugins/__init__.py", line 51, in is_my_business
[   65s]     action)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/plugins/__init__.py", line 113, in find_file_type_from_file_name
[   65s]     constants.FILE_TYPE_NOT_SUPPORTED_FMT % (file_type, action))
[   65s] FileTypeNotSupported: File type 'html' is not supported for write.
[   65s] -------------------- >> begin captured logging << --------------------
[   65s] pyexcel.internal.source_plugin.SourcePluginManager: DEBUG: load me now:sheet-read
[   65s] pyexcel.internal.source_plugin.SourcePluginManager: DEBUG: load me now:sheet-write
[   65s] --------------------- >> end captured logging << ---------------------
[   65s]
[   65s] ======================================================================
[   65s] ERROR: test_sheet_attributes.test_html_representation
[   65s] ----------------------------------------------------------------------
[   65s] Traceback (most recent call last):
[   65s]   File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
[   65s]     self.test(*self.arg)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/tests/test_sheet_attributes.py", line 109, in test_html_representation
[   65s]     eq_(str(sheet._repr_html_()), expected)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/meta.py", line 270, in _repr_html_
[   65s]     return self.html
[   65s] AttributeError: 'Sheet' object has no attribute 'html'
[   65s]
[   65s] ======================================================================
[   65s] ERROR: test_sheet_attributes.test_svg_representation
[   65s] ----------------------------------------------------------------------
[   65s] Traceback (most recent call last):
[   65s]   File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
[   65s]     self.test(*self.arg)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/tests/test_sheet_attributes.py", line 115, in test_svg_representation
[   65s]     io = sheet.plot()
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/meta.py", line 258, in plot
[   65s]     memory_content = self.save_to_memory(file_type, **keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/meta.py", line 285, in save_to_memory
[   65s]     **keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/core.py", line 42, in save_sheet
[   65s]     a_source = SOURCE.get_writable_source(**keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/source_plugin.py", line 91, in get_writable_source
[   65s]     **keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/source_plugin.py", line 65, in get_a_plugin
[   65s]     library=source_library, **keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/source_plugin.py", line 48, in load_me_now
[   65s]     _error_handler(action, **keywords)
[   65s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-0.5.7/pyexcel/internal/source_plugin.py", line 131, in _error_handler
[   65s]     constants.FILE_TYPE_NOT_SUPPORTED_FMT % (file_type, action))
[   65s] FileTypeNotSupported: File type 'svg' is not supported for write.
[   65s] -------------------- >> begin captured logging << --------------------
[   65s] pyexcel.internal.source_plugin.SourcePluginManager: DEBUG: load me now:sheet-write
[   65s] --------------------- >> end captured logging << ---------------------
[   65s]
[   65s] ======================================================================
[   65s] FAIL: test_file_type_as_attribute.test_invalid_json_setter
[   65s] ----------------------------------------------------------------------
[   65s] Traceback (most recent call last):
[   65s]   File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
[   65s]     self.test(*self.arg)
[   65s]   File "/usr/lib/python2.7/site-packages/nose/tools/nontrivial.py", line 67, in newfunc
[   65s]     raise AssertionError(message)
[   65s] AssertionError: test_invalid_json_setter() did not raise NotImplementedError
[   65s]
[   65s] ----------------------------------------------------------------------
[   65s] Ran 511 tests in 7.231s
[   65s]
[   65s] FAILED (errors=6, failures=1)
```

**Comment by jayvdb** [comment]
Note pyexcel-text and pyexcel-handsontable were not installed into the test environment, and I suspect some of the errors are due to that.

**Comment by jayvdb** [comment]
Adding `examples` to the source tarball fixes the first two.

Installing pyexcel-text fixed `test_invalid_json_setter`, but maybe this is still something which needs improvement - if pyexcel-text is not installed, something should be still raising `NotImplementedError` for json related methods.

`test_svg_representation` & `test_save_handsontable_html` are still broken, which I assume must both require `pyexcel-handsontable` (c.f. https://github.com/pyexcel/pyexcel/issues/169)

**Comment by jayvdb** [comment]
Failing at https://build.opensuse.org/package/show/home:jayvdb:pyexcel/python-pyexcel due to missing examples.

You can "branch" that to your own workarea in order to debug any problems.

**Comment by chfw** [comment]
Oh, no! Another release is required. I totally forgot that unit tests verify all code in examples folder.
