### ISSUE TITLE
Can't write xlsx file with program packaged with Pyinstaller

### ISSUE THREAD

**Issue by ozsolarwind** [pyexcel/pyexcel#210]
I am attempting to package a Python 3 program with Pyinstaller that outputs to a .xlsx file.
The program execute fine as a Python program but the packaged version fails when it attempts to write the file. The material below has the relevant part of the Python program, Pyinstaller Hidden Imports, pip freeze output and the failed execution output. Any help appreciated.

program part
============

import pyexcel as pxl
import pyexcel_ods
import pyexcel_xls
import pyexcel_xlsx
...

pxl.save_as(records=items, dest_file_name=datafile)

Pyinstaller Hidden Imports
==========================

hiddenimports=['pyexcel_io.database',
               'pyexcel_io.readers.csvr',
               'pyexcel_io.readers.csvz',
               'pyexcel_io.readers.tsv',
               'pyexcel_io.readers.tsvz',
               'pyexcel_io.writers.csvw',
               'pyexcel_io.readers.csvz',
               'pyexcel_io.readers.tsv',
               'pyexcel_io.readers.tsvz',
               'pyexcel_xls',
               'pyexcel_xls.xlsr',
               'pyexcel_xls.xlsw',
               'pyexcel_ods',
               'pyexcel_ods.odsr',
               'pyexcel_ods.odsw',
               'pyexcel.plugins.parsers.excel',
               'pyexcel.plugins.renderers',
               'pyexcel.plugins.renderers.excel',
               'pyexcel.plugins.sources.file_input',
               'pyexcel.plugins.sources.file_output',
               'pyexcel.plugins.sources.pydata.bookdict',
               'pyexcel.plugins.sources.pydata.dictsource',
               'pyexcel.plugins.sources.pydata.arraysource',
               'pyexcel.plugins.sources.pydata.records'],

pip freeze output
=================
...
openpyxl==3.0.3
pefile==2018.8.8
pyexcel==0.5.15
pyexcel-io==0.5.20
pyexcel-ods==0.5.6
pyexcel-xls==0.5.8
pyexcel-xlsx==0.5.8
PyInstaller==3.4
...
xlrd==1.2.0
XlsxWriter==1.2.9
xlwt==1.3.0

program execution
=================

G:\>catalogue.exe
Failed to import pyexcel_xlsx.xlsxw
Traceback (most recent call last):
  File "site-packages\lml\utils.py", line 64, in do_import_class
ModuleNotFoundError: No module named 'pyexcel_xlsx.xlsxw'
Traceback (most recent call last):
  File "catalogue.py", line 375, in exportDB
  File "functions.py", line 387, in export_catalogue
  File "site-packages\pyexcel\core.py", line 82, in save_as
  File "site-packages\pyexcel\internal\core.py", line 48, in save_sheet
  File "site-packages\pyexcel\internal\core.py", line 60, in _save_any
  File "site-packages\pyexcel\plugins\sources\file_output.py", line 33, in write_data
  File "site-packages\pyexcel\plugins\renderers\excel.py", line 28, in render_sheet_to_file
  File "site-packages\pyexcel_io\io.py", line 131, in save_data
  File "site-packages\pyexcel_io\io.py", line 147, in store_data
  File "site-packages\pyexcel_io\io.py", line 250, in get_writer
  File "site-packages\pyexcel_io\plugins.py", line 90, in get_a_plugin
  File "site-packages\lml\plugin.py", line 278, in load_me_now
  File "site-packages\lml\plugin.py", line 304, in dynamic_load_library
  File "site-packages\lml\utils.py", line 64, in do_import_class
ModuleNotFoundError: No module named 'pyexcel_xlsx.xlsxw'

**Comment by chfw** [comment]
It means you missed pyexcel_xlsx.xlsxw.

Please refer to the docs. Other pyexcel users were able to package it with pyinstaller.

**Comment by ozsolarwind** [comment]
Thanks. Pretty obvious once you pointed it out :-(
I guess I was trying to balance what could be done in hidden imports and what needed to be included withing the Python program

**Comment by CatNofishing** [comment]
Good work, thanks your libray: pyexcel.

**Comment by chfw** [comment]
it seems pyinstaller had this contribution package: https://github.com/pyinstaller/pyinstaller-hooks-contrib/search?q=pyexcel&unscoped_q=pyexcel
