### ISSUE TITLE
KeyError: '.ods'  on sheet = pe.get_book(file_name=f)

### ISSUE THREAD

**Issue by academay** [pyexcel/pyexcel#232]
I'm not sure where the problem comes from.

 - python 3.8.5
 - Kubuntu 20.04, 
 - ODS file created by libreoffice 7.0.3(dev) 
 - same error with every ODS file I tried.

These 2 lines of code taken directly from readme.me of this project.

```>>> import pyexcel as pe
>>> f = '/path/file.ods'
>>> sheet = pe.get_book(file_name=f)
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    sheet = pe.get_book(file_name=f)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel/core.py", line 47, in get_book
    book_stream = sources.get_book_stream(**keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel/internal/core.py", line 39, in get_book_stream
    sheets = a_source.get_data()
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel/plugins/sources/file_input.py", line 38, in get_data
    sheets = self.__parser.parse_file(self.__file_name, **self._keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel/plugins/parsers/excel.py", line 19, in parse_file
    return self._parse_any(file_name, **keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel/plugins/parsers/excel.py", line 40, in _parse_any
    sheets = get_data(anything, file_type=file_type, **keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_io/io.py", line 86, in get_data
    data, _ = _get_data(
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_io/io.py", line 105, in _get_data
    return load_data(**keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_io/io.py", line 191, in load_data
    reader.open(file_name, **keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_io/reader.py", line 47, in open
    self.reader = self.reader_class(
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_ods3/odsr.py", line 64, in __init__
    self.ods_book = ezodf.opendoc(file_alike_object)
  File "/home/dy/.local/lib/python3.8/site-packages/ezodf/document.py", line 54, in opendoc
    mime_type = __detect_mime_type(fm)
  File "/home/dy/.local/lib/python3.8/site-packages/ezodf/document.py", line 69, in __detect_mime_type
    mime_type = MIMETYPES[ext]
KeyError: '.ods'
>>> sheet = pe.get_book(file_name=f)
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    sheet = pe.get_book(file_name=f)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel/core.py", line 47, in get_book
    book_stream = sources.get_book_stream(**keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel/internal/core.py", line 39, in get_book_stream
    sheets = a_source.get_data()
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel/plugins/sources/file_input.py", line 38, in get_data
    sheets = self.__parser.parse_file(self.__file_name, **self._keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel/plugins/parsers/excel.py", line 19, in parse_file
    return self._parse_any(file_name, **keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel/plugins/parsers/excel.py", line 40, in _parse_any
    sheets = get_data(anything, file_type=file_type, **keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_io/io.py", line 86, in get_data
    data, _ = _get_data(
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_io/io.py", line 105, in _get_data
    return load_data(**keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_io/io.py", line 191, in load_data
    reader.open(file_name, **keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_io/reader.py", line 47, in open
    self.reader = self.reader_class(
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_ods3/odsr.py", line 64, in __init__
    self.ods_book = ezodf.opendoc(file_alike_object)
  File "/home/dy/.local/lib/python3.8/site-packages/ezodf/document.py", line 54, in opendoc
    mime_type = __detect_mime_type(fm)
  File "/home/dy/.local/lib/python3.8/site-packages/ezodf/document.py", line 69, in __detect_mime_type
    mime_type = MIMETYPES[ext]
KeyError: '.ods'
```

**Comment by chfw** [comment]
can you create an ods file and attach it here?

**Comment by academay** [comment]
I can't recreate.
