### ISSUE TITLE
get_book() restults in TypeError: 'set' object is not subscriptable

### ISSUE THREAD

**Issue by vildead** [pyexcel/pyexcel#271]
I am unable to load simple .xlsx with one sheet containing two rows and three columns

```python
>>> from pyexcel import *
>>> get_book(file_name="./test.xlsx", skip_hidden_sheets = False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vilem/git-projects/metadata-tools/env38/lib/python3.8/site-packages/pyexcel/core.py", line 47, in get_book
    book_stream = sources.get_book_stream(**keywords)
  File "/home/vilem/git-projects/metadata-tools/env38/lib/python3.8/site-packages/pyexcel/internal/core.py", line 38, in get_book_stream
    sheets = a_source.get_data()
  File "/home/vilem/git-projects/metadata-tools/env38/lib/python3.8/site-packages/pyexcel/plugins/sources/file_input.py", line 38, in get_data
    sheets = self.__parser.parse_file(self.__file_name, **self._keywords)
  File "/home/vilem/git-projects/metadata-tools/env38/lib/python3.8/site-packages/pyexcel/plugins/parsers/excel.py", line 19, in parse_file
    return self._parse_any(file_name, **keywords)
  File "/home/vilem/git-projects/metadata-tools/env38/lib/python3.8/site-packages/pyexcel/plugins/parsers/excel.py", line 40, in _parse_any
    sheets = get_data(anything, file_type=file_type, **keywords)
  File "/home/vilem/git-projects/metadata-tools/env38/lib/python3.8/site-packages/pyexcel_io/io.py", line 86, in get_data
    data, _ = _get_data(
  File "/home/vilem/git-projects/metadata-tools/env38/lib/python3.8/site-packages/pyexcel_io/io.py", line 105, in _get_data
    return load_data(**keywords)
  File "/home/vilem/git-projects/metadata-tools/env38/lib/python3.8/site-packages/pyexcel_io/io.py", line 205, in load_data
    result = reader.read_all()
  File "/home/vilem/git-projects/metadata-tools/env38/lib/python3.8/site-packages/pyexcel_io/reader.py", line 95, in read_all
    content_dict = self.read_sheet_by_index(sheet_index)
  File "/home/vilem/git-projects/metadata-tools/env38/lib/python3.8/site-packages/pyexcel_io/reader.py", line 84, in read_sheet_by_index
    sheet_reader = self.reader.read_sheet(sheet_index)
  File "/home/vilem/git-projects/metadata-tools/env38/lib/python3.8/site-packages/pyexcel_xlsx/xlsxr.py", line 148, in read_sheet
    sheet = SlowSheet(native_sheet, **self.keywords)
  File "/home/vilem/git-projects/metadata-tools/env38/lib/python3.8/site-packages/pyexcel_xlsx/xlsxr.py", line 72, in __init__
    for ranges in sheet.merged_cells.ranges[:]:
TypeError: 'set' object is not subscriptable
```

OS: Ubuntu 20.04
Pip freeze:
```bash
attrs==22.2.0
chardet==5.0.0
et-xmlfile==1.1.0
importlib-metadata==4.8.3
jsonschema==4.0.0
lml==0.1.0
openpyxl==3.1.1
pyexcel==0.7.0
pyexcel-io==0.6.6
pyexcel-xls==0.7.0
pyexcel-xlsx==0.6.0
pyrsistent==0.18.0
texttable==1.6.7
typing-extensions==4.1.1
xlrd==2.0.1
xlwt==1.3.0
zipp==3.6.0
```

**Comment by vildead** [comment]
Seems to be issue with my virtual environment :)

**Comment by vildead** [comment]
The issue is already reported in `pyexcel-xlsx` repo:  https://github.com/pyexcel/pyexcel-xlsx/issues/52

**Comment by kristianperkins** [comment]
> The issue is already reported in `pyexcel-xlsx` repo: [pyexcel/pyexcel-xlsx#52](https://github.com/pyexcel/pyexcel-xlsx/issues/52)

I would consider leaving this issue opan as this has effectively broken reading excel files since February which is an important issue of this package. Given the large chunk of functionality that is removed by this bug (inability to read xlsx files) along with the age of the issue should raise this as a larger problem.

If the plugin pyexcel-xlsx won't be fixed then pyexcel should find alternatives to reading xlsx files so that the package can continue to be effective.

You can recreate this error by running with a valid xlsx file `test.xlsx`:

```
pip install pyexcel pyexcel-xlsx
python -c "import pyexcel; pyexcel.get_sheet(file_name='test.xlsx')"
```
