### ISSUE TITLE
xls does not save itself as ods files do

### ISSUE THREAD

**Issue by Gryffoon** [pyexcel/pyexcel#30]
Let's consider thoose two codes : 

```
>>> import os, sys
>>> import pyexcel as pe
>>> import pyexcel.ext.ods3
>>> from pyexcel_ods3 import get_data, save_data
>>> al = pe.get_book(file_name="wb.ods")
>>> al
Sheet Name: Feuil1
+---+-------+
| A | B     |
+---+-------+
| 1 | alpha |
+---+-------+
| 2 | beta  |
+---+-------+
| 3 | gamma |
+---+-------+
>>> al.save_as("tst.ods")
>>> 
```
With the ods file everything is OK

And now this one:
```
>>> import os
>>> import sys
>>> import pyexcel as pe
>>> import pyexcel.ext.xls
>>> al = pyexcel.get_book(file_name="wb.xls")
>>> al
Sheet Name: Feuil1
+---+-------+
| A | B     |
+---+-------+
| 1 | alpha |
+---+-------+
| 2 | beta  |
+---+-------+
| 3 | gamma |
+---+-------+
>>> al.save_as("tst.xls")
Traceback (most recent call last):
  File "<pyshell#14>", line 1, in <module>
    al.save_as("tst.xls")
etc, etc, etc....
AttributeError: 'dict_items' object has no attribute 'sort'
```

Why by using the same coding we does not have the same success, we have an error with xls

**Comment by Gryffoon** [comment]
`pyexcel.save_book_as(bookdict=al, dest_file_name="tst.xls")` this does not work also

```
Traceback (most recent call last):
  File "<pyshell#17>", line 1, in <module>
    pyexcel.save_book_as(bookdict=al, dest_file_name="tst.xls")
etc, etc, etc...
line 194, in convert_dict_to_ordered_dict
    keys = the_dict.keys()
AttributeError: 'Book' object has no attribute 'keys'
```

So I found no solution to save as xls

**Comment by chfw** [comment]
I have tried your xls saving code and succeeded. I find one suspicious line here:

    >>> import pyexcel as pe # <--- import it as pe
    >>> import pyexcel.ext.xls
    >>> al = pyexcel.get_book(file_name="wb.xls") # but it is called as pyexcel, I am not sure it would work
    >>> al
    Sheet Name: Feuil1

As to save_book_as, you cannot supply pyexcel.Book to bookdict parameter. As the name suggests, it is book dict, which in pyexcel refers to a dictionary of sheet name and two dimensional array pair.

**Comment by Gryffoon** [comment]
```
>>> import os, sys
>>> import pyexcel as pe
>>> import pyexcel.ext.xls
>>> os.chdir("C:/Users/charafeddine.raghai/Documents/Transform Outp")
>>> al = pe.get_book(file_name="wb.xls")
>>> al
Sheet Name: Feuil1
+---+-------+
| A | B     |
+---+-------+
| 1 | alpha |
+---+-------+
| 2 | beta  |
+---+-------+
| 3 | gamma |
+---+-------+
>>> al.save_as("tst.xls")
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    al.save_as("tst.xls")
etc, etc, etc...
-packages\xlwt\Style.py", line 196, in _all_fonts
    alist.sort()
AttributeError: 'dict_items' object has no attribute 'sort'
```

So, this code didn't worked for me.
I'm usinge Python 3.5.1 with IDLE for Python3.5 64 bit

**Comment by chfw** [comment]
May I know your versions of pyexcel and pyexcel-xls? The ones I have used are: pyexcel==0.2.0 and pyexcel-xls==0.1.0

**Comment by Gryffoon** [comment]
pyexcel (0.2.0)
pyexcel-xls (0.1.0)
I use Python 3.5 64 bit on Windows 7 64 bit

```
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    al.save_as("tst.xls")
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel\book.py", line 238, in save_as
    self.save_to(out_source)
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel\book.py", line 229, in save_to
    source.write_data(self)
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel\sources\file.py", line 101, in write_data
    **self.keywords)
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel_io\__init__.py", line 296, in save_data
    **keywords)
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel_io\__init__.py", line 261, in store_data
    writer.close()
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel_xls\__init__.py", line 224, in close
    self.wb.save(self.file)
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\xlwt\Workbook.py", line 696, in save
    doc.save(filename_or_stream, self.get_biff_data())
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\xlwt\Workbook.py", line 653, in get_biff_data
    before += self.__all_fonts_num_formats_xf_styles_rec()
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\xlwt\Workbook.py", line 556, in __all_fonts_num_formats_xf_styles_rec
    return self.__styles.get_biff_data()
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\xlwt\Style.py", line 184, in get_biff_data
    result += self._all_fonts()
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\xlwt\Style.py", line 196, in _all_fonts
    alist.sort()
AttributeError: 'dict_items' object has no attribute 'sort'
```

**Comment by Gryffoon** [comment]
The bug (and the difference) may come from the fact that we don't use the same version of Python 
I'm using (on windows 7) the last stable version (3.5 on windows)

**Comment by chfw** [comment]
It is related to Python 3 where [sort() is no longer available](http://stackoverflow.com/questions/28039155/dict-items-object-has-no-attribute-sortreplace-min). For python 3, [xlwt-future](https://pypi.python.org/pypi/xlwt-future) is preferred over [xlwt](https://pypi.python.org/pypi/xlwt). Can you install xlwt-future instead and try?

**Comment by Gryffoon** [comment]
I have both:

xlrd (0.9.4)
xlwt (1.0.0)
xlwt-future (0.8.0)

**Comment by Gryffoon** [comment]
This is all what I have:
colorama (0.3.7)
Cython (0.23.4)
ezodf (0.3.2)
future (0.15.2)
jdcal (1.2)
lxml (3.6.0)
openpyxl (2.2.2)
pip (8.1.1)
pyexcel (0.2.0)
pyexcel-io (0.1.0)
pyexcel-ods3 (0.1.1)
pyexcel-text (0.1.1)
pyexcel-xls (0.1.0)
pyexcel-xlsx (0.1.0)
setuptools (18.2)
tablib (0.11.2)
tabulate (0.7.5)
termcolor (1.1.0)
texttable (0.8.4)
wget (3.2)
xlrd (0.9.4)
xlwt (1.0.0)
xlwt-future (0.8.0)

**Comment by chfw** [comment]
what if you pip uninstall xlwt?

**Comment by Gryffoon** [comment]
I've unisntalled it, it didn't changed anything at all.

```
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    al.save_as("tst.xls")
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel\book.py", line 238, in save_as
    self.save_to(out_source)
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel\book.py", line 229, in save_to
    source.write_data(self)
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel\sources\file.py", line 101, in write_data
    **self.keywords)
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel_io\__init__.py", line 296, in save_data
    **keywords)
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel_io\__init__.py", line 261, in store_data
    writer.close()
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel_xls\__init__.py", line 224, in close
    self.wb.save(self.file)
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\xlwt\Workbook.py", line 696, in save
    doc.save(filename_or_stream, self.get_biff_data())
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\xlwt\Workbook.py", line 653, in get_biff_data
    before += self.__all_fonts_num_formats_xf_styles_rec()
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\xlwt\Workbook.py", line 556, in __all_fonts_num_formats_xf_styles_rec
    return self.__styles.get_biff_data()
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\xlwt\Style.py", line 184, in get_biff_data
    result += self._all_fonts()
  File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\xlwt\Style.py", line 196, in _all_fonts
    alist.sort()
AttributeError: 'dict_items' object has no attribute 'sort'

```

**Comment by chfw** [comment]
Seems you are still using xlwt not xlwt-future. Evidence is here:

[xlwt Style.py line 196](https://github.com/python-excel/xlwt/blob/master/xlwt/Style.py#L196)
[xlwt-future Style.py line 196](https://github.com/PythonCharmers/xlwt-future/blob/master/xlwt/Style.py#L196)

**Comment by Gryffoon** [comment]
Now I've uninstalled xlwt with pip3 and not pip (pip is for python2.7), and this is what happens:

```
C:\>pip3 uninstall xlwt
Uninstalling xlwt-1.0.0:
```

This is what happens

```
>>> import os, sys
>>> import pyexcel as pe
>>> import pyexcel.ext.xls
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import pyexcel.ext.xls
  File "C:\Users\charafeddine.raghai\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel\exthook.py", line 111, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "C:\Users\charafeddine.raghai\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel\_compact.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\charafeddine.raghai\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel_xls\__init__.py", line 13, in <module>
    from xlwt import Workbook, XFStyle
ImportError: cannot import name 'Workbook'
```

**Comment by chfw** [comment]
right, now it seems xlwt is not present for python3 env. please then do pip3 install xlwt-future. 

It should work with xlwt-future beacause pyexcel is tested [against python 3.5 in travis](https://travis-ci.org/pyexcel/pyexcel/jobs/120726338#L313).

**Comment by Gryffoon** [comment]
```
Requirement already satisfied (use --upgrade to upgrade): xlwt-future in c:\users\charafeddine.raghai\appdata\local\programs\python\python35\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): future>=0.8.2 in c:\users\charafeddine.raghai\appdata\local\programs\python\python35\lib\site-packages (from xlwt-future)

```

**Comment by Gryffoon** [comment]
I already have it, I installed pyexcel-xls trough pip3

```
colorama (0.3.7)
Cython (0.23.4)
ezodf (0.3.2)
future (0.15.2)
jdcal (1.2)
lxml (3.6.0)
openpyxl (2.2.2)
pip (8.1.1)
pyexcel (0.2.0)
pyexcel-io (0.1.0)
pyexcel-ods3 (0.1.1)
pyexcel-text (0.1.1)
pyexcel-xls (0.1.0)
pyexcel-xlsx (0.1.0)
setuptools (18.2)
tablib (0.11.2)
tabulate (0.7.5)
termcolor (1.1.0)
texttable (0.8.4)
wget (3.2)
xlrd (0.9.4)
xlwt-future (0.8.0) 
```

**Comment by Gryffoon** [comment]
It seems that in pyexcel_xls file it import from xlwt and not from xlwt-future : 

```
File "C:\Users\Spiderman\AppData\Local\Programs\Python\Python35\lib\site-packages\pyexcel_xls\__init__.py", line 13, in <module>
    from xlwt import Workbook, XFStyle
```

**Comment by chfw** [comment]
yes, because xlwt-future is fork of xlwt and they share the same [xlwt package name space](https://github.com/PythonCharmers/xlwt-future).

**Comment by Gryffoon** [comment]
So, I have xlwt future but it does not import the function.

**Comment by Gryffoon** [comment]
So what do you suggest ?

**Comment by Gryffoon** [comment]
I uninstalled xlwt-future then reinstalled it, this solved the problem

**Comment by Gryffoon** [comment]
I've uninstalled xlwt-future then reinstalled it, this solved the problem

**Comment by chfw** [comment]
Thanks for sharing the solution. I was scratching my head.
