### ISSUE TITLE
moban fails with IOError due to missing directory commons

### ISSUE THREAD

**Issue by jayvdb** [pyexcel/pyexcel#39]
It appears a directory `commons`, specified in `.moban.yml`, is missing.

```
pyexcel]$ moban 
Traceback (most recent call last):
  File "/usr/bin/moban", line 9, in <module>
    load_entry_point('moban==0.0.2', 'console_scripts', 'moban')()
  File "/usr/lib/python2.7/site-packages/moban-0.0.2-py2.7.egg/moban/main.py", line 36, in main
    handle_moban_file(options)
  File "/usr/lib/python2.7/site-packages/moban-0.0.2-py2.7.egg/moban/main.py", line 93, in handle_moban_file
    handle_moban_file_v1(moban_file_configurations, options)
  File "/usr/lib/python2.7/site-packages/moban-0.0.2-py2.7.egg/moban/mobanfile.py", line 23, in handle_moban_file_v1
    engine.render_to_files(list_of_templating_parameters)
  File "/usr/lib/python2.7/site-packages/moban-0.0.2-py2.7.egg/moban/engine.py", line 42, in render_to_files
    self._render_with_finding_data_first(sta.data_file_index)
  File "/usr/lib/python2.7/site-packages/moban-0.0.2-py2.7.egg/moban/engine.py", line 56, in _render_with_finding_data_first
    data = self.context.get_data(data_file)
  File "/usr/lib/python2.7/site-packages/moban-0.0.2-py2.7.egg/moban/engine.py", line 68, in get_data
    return open_yaml(self.context_dirs, file_name)
  File "/usr/lib/python2.7/site-packages/moban-0.0.2-py2.7.egg/moban/utils.py", line 45, in open_yaml
    data.pop(LABEL_OVERRIDES))
  File "/usr/lib/python2.7/site-packages/moban-0.0.2-py2.7.egg/moban/utils.py", line 37, in open_yaml
    the_yaml_file = search_file(base_dir, file_name)
  File "/usr/lib/python2.7/site-packages/moban-0.0.2-py2.7.egg/moban/utils.py", line 62, in search_file
    the_file))
IOError: Both pyexcel.yaml and commons/config/pyexcel.yaml does not exist
```

**Comment by chfw** [comment]
I haven't had the time to update the short developer guide yet. What's needed is to issue the following command at your working directory:

    git clone https://github.com/pyexcel/pyexcel-commons.git commons

Plus, I am looking for a way to auto-checkout pyexcel-commons, instead of sub git repo.

**Comment by jayvdb** [comment]
Do you mean you are considering adding git cloning into moban?

My very uninformed initial impression is git submodule or git subtree is the way to go, at least temporarily, as it is a tiny and optional sub repo. Describing the dependency within git allows any tool to benefit from it.

Anyway, thx, ill play with it more now.

**Comment by chfw** [comment]
Outside moban. I am looking for a pythonic Makefile replacement. looked at fabric, but it is more ssh oriented.
