### ISSUE TITLE
IndexError: list index out of range for file with combined cells

### ISSUE THREAD

**Issue by Gabriel-p** [pyexcel/pyexcel#61]
The attached file [test.ods.tar.gz](https://github.com/pyexcel/pyexcel/files/530641/test.ods.tar.gz) contains a group of combined cells, as seen:

![screenshot from 2016-10-14 21 28 15](https://cloud.githubusercontent.com/assets/6054951/19406042/25ae7df2-9255-11e6-97bd-ade7c39ad66d.png)

Attempting to read it with

```
import pyexcel_ods as pe
pe.get_data('test.ods')
```
results in:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    pe.get_data('test.ods')
  File "/home/gabriel/.pyenv/versions/catalog-env/lib/python2.7/site-packages/pyexcel_ods/__init__.py", line 29, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/home/gabriel/.pyenv/versions/catalog-env/lib/python2.7/site-packages/pyexcel_io/io.py", line 34, in get_data
    data[key] = list(data[key])
  File "/home/gabriel/.pyenv/versions/catalog-env/lib/python2.7/site-packages/pyexcel_io/sheet.py", line 83, in to_array
    cell_value = self._cell_value(row, column)
  File "/home/gabriel/.pyenv/versions/catalog-env/lib/python2.7/site-packages/pyexcel_ods/ods.py", line 64, in _cell_value
    cell_value = row_cache[column]
IndexError: list index out of range
```

**Comment by chfw** [comment]
reproduced and moved to pyexcel-ods.
