### ISSUE TITLE
UnboundLocalError: local variable 'xls_book' referenced before assignment

### ISSUE THREAD

**Issue by Scit** [pyexcel/pyexcel#67]
I'm trying to use pyexcel with django. I've written a test like so:

```
class TestUploadedFile(APITestCase):
    def test_1(self):
        rows = [["data1", " ", " "], ["data2", " ", " "], ["data3", " ", " "]]
        sheet = pyexcel.Sheet(rows)
        file = InMemoryUploadedFile(BytesIO(sheet.xls), None, 'filename.xls', 'application/vnd.ms-excel', None, None)
        file.seek(0)

        data =  {'file': file}
        response = self.client.post(self.url, data, format='multipart')
```

In the view I read my file using django-excel:

```
   def perform_create(self, serializer):
        uploaded_file = serializer.save()
        file = serializer.validated_data['file']
        file.get_array()

```

So, what I got:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/viewsets.py", line 83, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/project/api/viewsets.py", line 69, in dispatch
    return super(ProjectModelView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/project/api/files/views/uploaded_file.py", line 31, in create
    return super(UploadedFile, self).create(request, **kwargs)
  File "/app/project/api/viewsets.py", line 19, in create
    return super(BulkCreateModelMixin, self).create(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/project/api/files/views/trader_uploaded_file.py", line 38, in perform_create
    file.get_array()
  File "/usr/local/lib/python3.5/site-packages/pyexcel_webio/__init__.py", line 81, in get_array
    return pe.get_array(**params)
  File "/usr/local/lib/python3.5/site-packages/pyexcel/core.py", line 232, in get_array
    sheet = get_sheet(**keywords)
  File "/usr/local/lib/python3.5/site-packages/pyexcel/core.py", line 66, in get_sheet
    named_content = sources.get_sheet_stream(**keywords)
  File "/usr/local/lib/python3.5/site-packages/pyexcel/sources/__init__.py", line 15, in get_sheet_stream
    sheets = source.get_data()
  File "/usr/local/lib/python3.5/site-packages/pyexcel/sources/file_source_input.py", line 84, in get_data
    **self.keywords)
  File "/usr/local/lib/python3.5/site-packages/pyexcel_io/io.py", line 28, in get_data
    file_type=file_type, **keywords)
  File "/usr/local/lib/python3.5/site-packages/pyexcel_io/io.py", line 130, in load_data_new
    result = reader.read_all()
  File "/usr/local/lib/python3.5/site-packages/pyexcel_xls/xls.py", line 113, in read_all
    self.native_book = self._get_book()
  File "/usr/local/lib/python3.5/site-packages/pyexcel_xls/xls.py", line 140, in _get_book
    return xls_book
UnboundLocalError: local variable 'xls_book' referenced before assignment
```

What the problem is in?

**Comment by chfw** [comment]
First of all, it is interesting to see how django-excel works together with django rest framework. It is a new challenge. rest frame work had its own [fileuploadparser](http://www.django-rest-framework.org/api-guide/parsers/#fileuploadparser) and it should respect django upload handler. But I doubted it. 

> Parses raw file upload content. The request.data property will be a dictionary with a single key 'file' containing the uploaded file.

> If the view used with FileUploadParser is called with a filename URL keyword argument, then that argument will be used as the filename.

Can you put a break point at https://github.com/pyexcel/django-excel/blob/master/django_excel/__init__.py#L26? And dump the params at https://github.com/pyexcel/pyexcel-webio/blob/master/pyexcel_webio/__init__.py#L80?

My initial judgement is the parameters to pyexcel are not complete.

**Comment by Scit** [comment]
`{'file_type': 'xls', 'file_content': b''}`

**Comment by chfw** [comment]
It looks the iostream has been read. Hence file.read() return empty buffer. 

       def perform_create(self, serializer):
            uploaded_file = serializer.save() # <- is it possible that this has consumed the stream.
            file = serializer.validated_data['file'] 
            file.get_array()

What if you do not call save()?

**Comment by Scit** [comment]
Yes! You're right! Thank you!
file.seek(0) solves this problem.
