### ISSUE TITLE
merge workbooks doesn't support xlsm

### ISSUE THREAD

**Issue by SimonTulettIdeaco** [pyexcel/pyexcel#70]
when trying to load an xlsm workbook using the get_workbook method I get the following error.

IOError: No suitable library found for xlsm

The full stack trace is below.

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.1\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.1\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/simon/PycharmProjects/AdviceActivityReporting/combine_practice_reports.py", line 98, in <module>
    main()
  File "C:/Users/simon/PycharmProjects/AdviceActivityReporting/combine_practice_reports.py", line 76, in main
    wb_wip = pyexcel.load_book('{0}\{1}\{2}.xlsm'.format(zip_wip_directory, wip_unzipped_folder, f1))
  File "C:\Users\simon\AMP_Python27_VEnv\lib\site-packages\pyexcel\_compact.py", line 76, in inner
    return func(*arg, **keywords)
  File "C:\Users\simon\AMP_Python27_VEnv\lib\site-packages\pyexcel\deprecated.py", line 31, in load_book
    return get_book(file_name=file_name, **keywords)
  File "C:\Users\simon\AMP_Python27_VEnv\lib\site-packages\pyexcel\core.py", line 103, in get_book
    book_stream = sources.get_book_stream(**keywords)
  File "C:\Users\simon\AMP_Python27_VEnv\lib\site-packages\pyexcel\sources\__init__.py", line 28, in get_book_stream
    sheets = source.get_data()
  File "C:\Users\simon\AMP_Python27_VEnv\lib\site-packages\pyexcel\sources\file_source_input.py", line 55, in get_data
    sheets = get_data(self.__file_name, streaming=True, **self.__keywords)
  File "C:\Users\simon\AMP_Python27_VEnv\lib\site-packages\pyexcel_io\io.py", line 36, in get_data
    file_type=file_type, **keywords)
  File "C:\Users\simon\AMP_Python27_VEnv\lib\site-packages\pyexcel_io\io.py", line 126, in load_data
    reader = manager.create_reader(file_type, library)
  File "C:\Users\simon\AMP_Python27_VEnv\lib\site-packages\pyexcel_io\manager.py", line 138, in create_reader
    reader_factories, file_type, library)
  File "C:\Users\simon\AMP_Python27_VEnv\lib\site-packages\pyexcel_io\manager.py", line 174, in _get_a_handler
    raise IOError("No suitable library found for %s" % file_type)
IOError: No suitable library found for xlsm

**Comment by chfw** [comment]
Have you installed pyexcel-xls ? What does 'pip freeze' show?

**Comment by SimonTulettIdeaco** [comment]
Yep it looks like I was missing a dependency, thank you.

When merging two workbooks is there anyway of defining the sheet names for the new merged book? I am running into sheet name length issues.

**Comment by chfw** [comment]
Since load_book was used, you could use the returned book instance to access the name of its sheets. 

    >>> import pyexcel as p
    >>> content = {'A': [[1]]}
    >>> b = p.get_book(bookdict=content)
    >>> b
    A:
    +---+
    | 1 |
    +---+
    >>> b[0].name
    'A'
    >>> b[0].name = 'B'
    >>> b
    B:
    +---+
    | 1 |
    +---+
And btw, load_book is deprecated, please use get_book instead.
