### ISSUE TITLE
No suitable library found for xlsx

### ISSUE THREAD

**Issue by baddison2005** [pyexcel/pyexcel#86]
Ever since I upgraded my version of Python from 3.5 to 3.6 (3.6.1 to be exact) with the latest version of pyexcel (0.5.0), I have not been able to read into Python .xlsx files. For example, when I run the following commands:
`import pyexcel # import it to handle xlsx files`
`m_dwarfs_photo_file = \
 '/Users/brettaddison/Dropbox/STARCHIVE/Brett/Photometry_table_extracted_Solar_Neighborhood_M_Dwarfs.xlsx'`
`photometry_sheet = pyexcel.get_sheet(file_name=m_dwarfs_photo_file, sheet_name="Sheet1", name_columns_by_row=0)`

I get the following error messages:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyexcel_io/manager.py", line 200, in create_reader
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyexcel_io/manager.py", line 264, in _get_a_handler
pyexcel_io.manager.NoSupportingPluginFound: No suitable library found for xlsx
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-d904165e380a>", line 1, in <module>
    photometry_sheet = pyexcel.get_sheet(file_name=m_dwarfs_photo_file, sheet_name="Sheet1", name_columns_by_row=0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyexcel/core.py", line 67, in get_sheet
    named_content = sources.get_sheet_stream(**keywords)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyexcel/sources/__init__.py", line 15, in get_sheet_stream
    sheets = source.get_data()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyexcel/sources/file_source_input.py", line 55, in get_data
    sheets = get_data(self.__file_name, streaming=True, **self.__keywords)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyexcel_io/io.py", line 41, in get_data
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyexcel_io/io.py", line 135, in load_data
    else:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyexcel_io/manager.py", line 211, in create_reader
pyexcel_io.manager.SupportingPluginAvailableButNotInstalled: Please install one of these plugins for read data in 'xlsx': pyexcel-xls,pyexcel-xlsx
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2879, in run_code
    self.showtraceback(running_compiled_code=True)
TypeError: showtraceback() got an unexpected keyword argument 'running_compiled_code'

Note, I have installed pyexcel_xlsx and pyexcel_xls using pip. This worked in previous versions of Python. Not sure what this is failing in this version of Python and pyexcel.

Cheers,
Brett

**Comment by chfw** [comment]
Please print a list of pyexcel libraries. New release 0.5.0 needs all plugins to be 0.4.0.

**Comment by chfw** [comment]
here the plugin compatibility table: http://pyexcel.readthedocs.io/en/latest/#id5

**Comment by baddison2005** [comment]
Here is a list of my pyexcel libraries:
ws148-54:.ssh brettaddison$ sudo pip freeze | grep pyexcel
Password:
The directory '/Users/brettaddison/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
pyexcel==0.5.0
pyexcel-io==0.4.0
pyexcel-xls==0.4.0
pyexcel-xlsx==0.4.0

**Comment by chfw** [comment]
Hi, I think pyexcel-io package in your environment where the problem is reproduced, is v0.3.x 

See the manager.py in pyexcel-io v0.4.0 has only 74 lines of code.

https://github.com/pyexcel/pyexcel-io/blob/v0.4.x/pyexcel_io/manager.py

So what you can do is:

    $ pip uninstall pyexcel-io

And keep doing it until there is not pyexcel-io package. Then install pyexcel-io.

**Comment by baddison2005** [comment]
This worked! Thanks for your help!

Cheers,
Brett

**Comment by chfw** [comment]
my pleasure.
