### ISSUE TITLE
get KeyError: u'email' when dealing data with pymongo

### ISSUE THREAD

**Issue by AkashiWen** [pyexcel/pyexcel#92]
here is one of my result from pymongo:
```
{u'phone': None, u'_id': ObjectId('586d235d5f0712767415bbcb'), u'name': u'\u738b\u9e6d\u878d', u'email': u'727871677@qq.com'}
```
which contains 'u' chars

then I got KeyError: u'email'

is it necessary to find a way to remove the 'u'..?

**Comment by chfw** [comment]
How did you get the error when using pyexcel? `u` means unicode. No need to remove it. Show me the code.

**Comment by AkashiWen** [comment]
code is quite simple I think:
```
#coding:utf-8
import pyexcel
...
...
## search in users
users = db.users.find({ '_id': { '$in': userIdList } },
    { 'name': 1, 'email': 1, 'phone': 1 })
## I tried users = list(users) here, but not work.
pyexcel.save_as(records=users, dest_file_name=course['name'] + ".xlsx")
```

one of users prints like:
```
{u'phone': u'18855619808', u'_id': ObjectId('596e2e2c3b43e66af8f656ce'), u'name': u'wm713041510'}
```

**Comment by chfw** [comment]
I see. It was assumed in-coming record had the the same keys and use the keys of first dictionary as a reference. 

https://github.com/pyexcel/pyexcel/blob/master/pyexcel/plugins/sources/pydata/common.py#L60. 

Changes can be to accommodate missing keys in the subsequent dictionaries. And a complete list of keys need to be told to pyexcel when and if the first dictionary does not have all keys. 

So, will look into it later.

**Comment by chfw** [comment]
Please verify it using the master branch:

    pip install https://github.com/pyexcel/pyexcel/archive/master.zip

**Comment by AkashiWen** [comment]
thx for your quick reply, but emmmm... get another err log(ValueError):
```
Traceback (most recent call last):
  File "for-each-courses.py", line 31, in <module>
    pyexcel.save_as(records=users, dest_file_name=course['name'] + ".xlsx")
  File "/usr/local/lib/python2.7/site-packages/pyexcel/core.py", line 66, in save_as
    return sources.save_sheet(sheet, **dest_keywords)
  File "/usr/local/lib/python2.7/site-packages/pyexcel/internal/core.py", line 43, in save_sheet
    return _save_any(a_source, sheet)
  File "/usr/local/lib/python2.7/site-packages/pyexcel/internal/core.py", line 55, in _save_any
    a_source.write_data(instance)
  File "/usr/local/lib/python2.7/site-packages/pyexcel/plugins/sources/file_output.py", line 29, in write_data
    sheet, **self._keywords)
  File "/usr/local/lib/python2.7/site-packages/pyexcel/plugins/renderers/excel.py", line 27, in render_sheet_to_file
    save_data(file_name, data, **keywords)
  File "/usr/local/lib/python2.7/site-packages/pyexcel_io/io.py", line 119, in save_data
    **keywords)
  File "/usr/local/lib/python2.7/site-packages/pyexcel_io/io.py", line 141, in store_data
    writer.write(data)
  File "/usr/local/lib/python2.7/site-packages/pyexcel_io/book.py", line 193, in write
    sheet_writer.write_array(incoming_dict[sheet_name])
  File "/usr/local/lib/python2.7/site-packages/pyexcel_io/sheet.py", line 160, in write_array
    self.write_row(row)
  File "/usr/local/lib/python2.7/site-packages/pyexcel_xlsx/xlsxw.py", line 28, in write_row
    self._native_sheet.append(array)
  File "/usr/local/lib/python2.7/site-packages/openpyxl/writer/write_only.py", line 236, in append
    self.writer.send(row)
  File "/usr/local/lib/python2.7/site-packages/openpyxl/writer/write_only.py", line 171, in _write_header
    raise ValueError
ValueError
```

**Comment by chfw** [comment]
Or you need to format it as a primitive type.

**Comment by chfw** [comment]
Please be notified that I am changing 'keys' to 'custom_headers' when you call `pyexcel.save_as(records=users, custom_headers=['a', 'b', 'c'], dest_file_name=course['name'] + ".xlsx")`

What's more, if you data is big, you are advised to use `isave_as` instead.
