### ISSUE TITLE
Crashes on capitalized file extensions

### ISSUE THREAD

**Issue by brookcub** [pyexcel/pyexcel#98]
This is crashing when I try to convert a file named "BTO JUNE EOF.XLS" from xls to csv. It works fine if I rename the file to "BTO JUNE EOF.xls".
```
Traceback (most recent call last):
  File "convert_to_csv2.2.py", line 95, in <module>
    convert(OUTPUT_FOLDER)
  File "convert_to_csv2.2.py", line 32, in convert
    convert(f)
  File "convert_to_csv2.2.py", line 36, in convert
    pyexcel.get_book(file_name=f).save_as(newFileName)
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\pyexcel\sources\__init__.py", line 235, in get_book
    book_stream = _get_book(**keywords)
  File "C:\Program Files (x86)\Python\Python35-32\lib\site-packages\pyexcel\sources\__init__.py", line 202, in _get_book
    raise NotImplementedError(MESSAGE_ERROR_NO_HANDLER)
NotImplementedError: No suitable plugins imported or installed

**Comment by chfw** [comment]
Which version of pyexcel are you having?

Capital file extension was fixed in 2016: https://github.com/pyexcel/pyexcel-xls/issues/11

**Comment by chfw** [comment]
Please re-open if the problem persists.
