### ISSUE TITLE
ValueError (writing xlsx) (pymongo)

### ISSUE THREAD

**Issue by AkashiWen** [pyexcel/pyexcel#99]
I have a dict and list
when assignment list to dict like:
```
dict['key'] = list
```
and try to write:
```
pyexcel.save_as()
```
then this error will happen

full log is: 
```
Traceback (most recent call last):
  File "for-each-course.py", line 43, in <module>
    pyexcel.save_as(records=parentList, dest_file_name=course['name'] + '.xlsx')
  File "/usr/local/lib/python2.7/site-packages/pyexcel/core.py", line 66, in save_as
    return sources.save_sheet(sheet, **dest_keywords)
  File "/usr/local/lib/python2.7/site-packages/pyexcel/internal/core.py", line 43, in save_sheet
    return _save_any(a_source, sheet)
  File "/usr/local/lib/python2.7/site-packages/pyexcel/internal/core.py", line 55, in _save_any
    a_source.write_data(instance)
  File "/usr/local/lib/python2.7/site-packages/pyexcel/plugins/sources/file_output.py", line 29, in write_data
    sheet, **self._keywords)
  File "/usr/local/lib/python2.7/site-packages/pyexcel/plugins/renderers/excel.py", line 27, in render_sheet_to_file
    save_data(file_name, data, **keywords)
  File "/usr/local/lib/python2.7/site-packages/pyexcel_io/io.py", line 119, in save_data
    **keywords)
  File "/usr/local/lib/python2.7/site-packages/pyexcel_io/io.py", line 141, in store_data
    writer.write(data)
  File "/usr/local/lib/python2.7/site-packages/pyexcel_io/book.py", line 193, in write
    sheet_writer.write_array(incoming_dict[sheet_name])
  File "/usr/local/lib/python2.7/site-packages/pyexcel_io/sheet.py", line 160, in write_array
    self.write_row(row)
  File "/usr/local/lib/python2.7/site-packages/pyexcel_xlsx/xlsxw.py", line 28, in write_row
    self._native_sheet.append(array)
  File "/usr/local/lib/python2.7/site-packages/openpyxl/writer/write_only.py", line 236, in append
    self.writer.send(row)
  File "/usr/local/lib/python2.7/site-packages/openpyxl/writer/write_only.py", line 171, in _write_header
    raise ValueError
ValueError
```

my part of code(attention p['children'] = children): 
```
courses = c.find({ 'price': { '$gt': 0 }, 'hide': False }).limit(2)

def is_parent(l):
	return l.get('parentId') is None

def filter_by_parent(lectures, parentId):
	return filter(lambda l : l.get('parentId') is not None and l['parentId'] == parentId, lectures)

for course in courses:
	print(course['name'])
	lectures = db.lectures.find({
		'courseId': ObjectId(course['_id']), 'hide': False 
	}, {
		'name': 1, 'parentId': 1
	}).sort('order', 1)
	lectures = list(lectures)
	parentList = filter(is_parent, lectures)
	i = 1
	for p in parentList:
		children = filter_by_parent(lectures, p['_id'])
		j = 1
		for child in children:
			child.pop('_id', None)
			child.pop('parentId', None)
			child['name'] = str(i) + '.' + str(j) + '.' + child['name']
			j += 1
			pass
		p['children'] = children ## emmmmmm......
		p.pop('_id', None)
		p['name'] = str(i) + '.' + p['name']
		i += 1
		pass
	pyexcel.save_as(records=parentList, dest_file_name=course['name'] + '.xlsx')
```

**Comment by chfw** [comment]
Some sample content in parentList? What does its structure look like?

**Comment by AkashiWen** [comment]
```
[
    {
        u'name': u'1.\u5316\u5b66\u5b9e\u9a8c\u5ba4\u57fa\u672c\u65b9\u6cd5',
        'children': [
            {
                u'name': u'1.1.\u5b9e\u9a8c\u5ba4\u5b89\u5168'
            },
            {
                u'name': u'1.2.\u7c97\u76d0\u63d0\u7eaf\uff0d\u8fc7\u6ee4\u4e0e\u84b8\u53d1'
            },
            {
                u'name': u'1.3.\u7c97\u76d0\u63d0\u7eaf\uff0d\u79bb\u5b50\u68c0\u9a8c\u4e0e\u63d0\u7eaf'
            },
            {
                u'name': u'1.4.\u84b8\u998f'
            },
            {
                u'name': u'1.5.\u8403\u53d6\u5206\u6db2'
            }
        ]
    },
    {
        u'name': u'2.\u5316\u5b66\u8ba1\u91cf\u5728\u5b9e\u9a8c\u4e2d\u7684\u5e94\u7528',
        'children': [
            {
                u'name': u'2.1.\u7269\u8d28\u7684\u91cf\u7684\u5355\u4f4d-\u6469\u5c14'
            },
            {
                u'name': u'2.2.\u6469\u5c14\u8d28\u91cf'
            },
            {
                u'name': u'2.3.\u6c14\u4f53\u6469\u5c14\u4f53\u79ef'
            },
            {
                u'name': u'2.4.\u963f\u4f0f\u4f3d\u5fb7\u7f57\u5b9a\u5f8b'
            },
            {
                u'name': u'2.5.\u7269\u8d28\u7684\u91cf\u6d53\u5ea6'
            },
            {
                u'name': u'2.6.\u4e00\u5b9a\u7269\u8d28\u7684\u91cf\u6d53\u5ea6\u6eb6\u6db2\u7684\u914d\u5236'
            }
        ]
    },
    {
        u'name': u'3.\u7269\u8d28\u7684\u5206\u7c7b',
        'children': [
            {
                u'name': u'3.1.\u5206\u7c7b\u6cd5'
            },
            {
                u'name': u'3.2.\u7269\u8d28\u7684\u5206\u7c7b'
            },
            {
                u'name': u'3.3.\u6df7\u5408\u7269\u7684\u5206\u7c7b\u53ca\u5206\u6563\u7cfb'
            },
            {
                u'name': u'3.4.\u80f6\u4f53\u7684\u7ed3\u6784\u4e0e\u6027\u8d28'
            }
        ]
    },
    {
        u'name': u'4.\u79bb\u5b50\u53cd\u5e94',
        'children': [
            {
                u'name': u'4.1.\u7535\u79bb\u548c\u7535\u89e3\u8d28'
            },
            {
                u'name': u'4.2.\u91cd\u65b0\u8ba4\u8bc6\u9178\u78b1\u76d0'
            },
            {
                u'name': u'4.3.\u79bb\u5b50\u53cd\u5e94\u7684\u5b9e\u8d28'
            },
            {
                u'name': u'4.4.\u79bb\u5b50\u65b9\u7a0b\u5f0f\u7684\u4e66\u5199'
            }
        ]
    },
    {
        u'name': u'5.\u6c27\u5316\u8fd8\u539f\u53cd\u5e94',
        'children': [
            {
                u'name': u'5.1.\u6c27\u5316\u8fd8\u539f\u53cd\u5e94'
            },
            {
                u'name': u'5.2.\u6c27\u5316\u8fd8\u539f\u53cd\u5e94\u7684\u5b9e\u8d28'
            },
            {
                u'name': u'5.3.\u6c27\u5316\u5242\u4e0e\u8fd8\u539f\u5242-\u6982\u5ff5\u7406\u89e3'
            },
            {
                u'name': u'5.4.\u6c27\u5316\u5242\u4e0e\u8fd8\u539f\u5242-\u5e38\u89c1\u7684\u6c27\u5316\u5242\u4e0e\u8fd8\u539f\u5242'
            },
            {
                u'name': u'5.5.\u53cc\u7ebf\u6865\\\u5355\u7ebf\u6865\u6cd5\u5206\u6790\u6c27\u5316\u8fd8\u539f\u53cd\u5e94'
            }
        ]
    },
    {
        u'name': u'6.\u91d1\u5c5e\u603b\u8bba',
        'children': [
            {
                u'name': u'6.1.\u91d1\u5c5e\u7684\u901a\u6027'
            },
            {
                u'name': u'6.2.\u91d1\u5c5e\u4e0e\u975e\u91d1\u5c5e\u53cd\u5e94'
            },
            {
                u'name': u'6.3.\u91d1\u5c5e\u4e0e\u6c34\u548c\u9178\u53cd\u5e94'
            },
            {
                u'name': u'6.4.\u94dd\u548c\u6c22\u6c27\u5316\u94a0\u7684\u53cd\u5e94'
            },
            {
                u'name': u'6.5.\u7269\u8d28\u7684\u91cf\u5728\u5316\u5b66\u8ba1\u7b97\u4e2d\u7684\u5e94\u7528'
            }
        ]
    },
    {
        u'name': u'7.\u94a0\u7684\u5316\u5408\u7269',
        'children': [
            {
                u'name': u'7.1.\u6c27\u5316\u94a0\u548c\u8fc7\u6c27\u5316\u94a0'
            },
            {
                u'name': u'7.2.\u78b3\u9178\u94a0\u548c\u78b3\u9178\u6c22\u94a0'
            }
        ]
    },
    {
        u'name': u'8.\u94dd\u7684\u5316\u5408\u7269',
        'children': [
            {
                u'name': u'8.1.\u6c27\u5316\u94dd\u548c\u6c22\u6c27\u5316\u94dd'
            },
            {
                u'name': u'8.2.\u94dd\u76d0\u548c\u504f\u94dd\u9178\u76d0'
            }
        ]
    },
    {
        u'name': u'9.\u94c1\u7684\u5316\u5408\u7269',
        'children': [
            {
                u'name': u'9.1.\u94c1\u7684\u6c27\u5316\u7269'
            },
            {
                u'name': u'9.2.\u94c1\u7684\u6c22\u6c27\u5316\u7269'
            },
            {
                u'name': u'9.3.\u94c1\u76d0\u548c\u4e9a\u94c1\u76d0'
            },
            {
                u'name': u'9.4.\u7528\u9014\u5e7f\u6cdb\u7684\u91d1\u5c5e\u6750\u6599'
            }
        ]
    },
    {
        u'name': u'10.\u7845',
        'children': [
            {
                u'name': u'10.1.\u4e8c\u6c27\u5316\u7845\u548c\u7845\u9178'
            },
            {
                u'name': u'10.2.\u7845\u9178\u76d0'
            },
            {
                u'name': u'10.3.\u7845\u5355\u8d28'
            }
        ]
    },
    {
        u'name': u'11.\u6c2f',
        'children': [
            {
                u'name': u'11.1.\u6c2f\u6c14\u7684\u5236\u5907-\u539f\u7406'
            },
            {
                u'name': u'11.2.\u6c2f\u6c14\u7684\u5236\u5907-\u88c5\u7f6e'
            },
            {
                u'name': u'11.3.\u6c2f\u6c14\u7684\u6027\u8d28'
            }
        ]
    },
    {
        u'name': u'12.\u786b\u548c\u6c2e\u7684\u6c27\u5316\u7269',
        'children': [
            {
                u'name': u'12.1.\u786b\u7684\u6c27\u5316\u7269'
            },
            {
                u'name': u'12.2.\u6c2e\u7684\u6c27\u5316\u7269'
            }
        ]
    },
    {
        u'name': u'13.\u6c28\\\u786b\u9178\\\u785d\u9178',
        'children': [
            {
                u'name': u'13.1.\u6d53\u786b\u9178\u7684\u6c27\u5316\u6027'
            },
            {
                u'name': u'13.2.\u785d\u9178\u7684\u6c27\u5316\u6027'
            },
            {
                u'name': u'13.3.\u6c28'
            },
            {
                u'name': u'13.4.\u94f5\u76d0\u3001\u6c28\u6c14\u7684\u5236\u53d6'
            }
        ]
    }
]
```

**Comment by chfw** [comment]
OK, the data structure for records is: a list of dictinaries, where individual dictionary should be simple key-value pair. In your case, you need to convert it as a single dictionary: as {.. u'13.\u6c28\\\u786b\u9178\\\u785d\u9178': [u'13.1.\u6d53\u786b\u9178\u7684\u6c27\u5316\u6027', u'13.2.\u785d\u9178\u7684\u6c27\u5316\u6027'..]}.

And then update parameter from `records=..` to `adict=...`

**Comment by AkashiWen** [comment]
after refactoring I got data: 
```
```

**Comment by chfw** [comment]
You are very close. Please find an example of [a_dictionary_of_one_dimensional_arrays](http://pyexcel.readthedocs.io/en/latest/design.html#examples-of-supported-data-structure)

**Comment by AkashiWen** [comment]
thank you, I guess that will be a_dictionary_of_one_dimensional_arrays.

**Comment by chfw** [comment]
```
>>> a_dictionary_of_one_dimensional_arrays = {
...     "Column 1": [1, 2, 3, 4],
...     "Column 2": [5, 6, 7, 8],
...     "Column 3": [9, 10, 11, 12],
... }
>>> p.get_sheet(adict=a_dictionary_of_one_dimensional_arrays)
pyexcel_sheet1:
+----------+----------+----------+
| Column 1 | Column 2 | Column 3 |
+----------+----------+----------+
| 1        | 5        | 9        |
+----------+----------+----------+
| 2        | 6        | 10       |
+----------+----------+----------+
| 3        | 7        | 11       |
+----------+----------+----------+
| 4        | 8        | 12       |
+----------+----------+----------+
```

You need to use save_as(adict=your_dict_instance..)

**Comment by chfw** [comment]
I see. You got it.
